### ISSUE TITLE
Use .sN in the version to denote sociomantic releases

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic-tsunami/ebtree#13]
Just for the sake of consistency, use `.sN` (where N is an incremental number) to denote sociomantic-specific releases. So next release should be: `v6.0.s7`.

**Comment by nemanja-boric-sociomantic** [comment]
https://github.com/sociomantic-tsunami/ebtree/releases/tag/v6.0.s7-rc5

**Comment by leandro-lucarella-sociomantic** [comment]
This change breaks version ordering, so we might need to start using a [Debian version epoch](http://www.fifi.org/doc/debian-policy/policy.html/ch-versions.html) for this. So `1:6.0.s7-rc5` in this case.

**Comment by nemanja-boric-sociomantic** [comment]
Looks like we need to change the packaging script to set the epoch on the new packages.

**Comment by nemanja-boric-sociomantic** [comment]
#14

**Comment by daniel-zullo** [comment]
Debian version epoch was implemented/merged in #14 and the version ordering is working fine.
